### ISSUE TITLE
Tapping minus points is buggy

### ISSUE THREAD

**Issue by micheljung** [Sutherlandon/qwixx-app#7]
Android 10/Chrome

It selects the X which opens that lookup bar at the bottom.
Once you tap somewhere else, the X is removed

![Screenshot_20201229-205134](https://user-images.githubusercontent.com/1864183/103310943-393f0000-4a19-11eb-9fcd-8734e7eb8b8d.png)

**Comment by Sutherlandon** [comment]
Thanks @micheljung for taking the time to submit this issue.  I've identified the issue and will be deploying a fix soon.  Thanks for playing!

**Comment by Sutherlandon** [comment]
The fix has been deployed.  Please let me know if you have any other feedback or find more issues.
